--
-- PostgreSQL database dump
--

\restrict x0QVCea51D2EJqKtAAJ0Jtjz4Fl85WzT027S925BYI1pnhY5e9Sc2QZzVYZGTrp

-- Dumped from database version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public."WebUsers" DROP CONSTRAINT "PK_WebUsers";
DROP TABLE public."WebUsers";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: WebUsers; Type: TABLE; Schema: public; Owner: sergey
--

CREATE TABLE public."WebUsers" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."WebUsers" OWNER TO sergey;

--
-- Name: WebUsers_Id_seq; Type: SEQUENCE; Schema: public; Owner: sergey
--

ALTER TABLE public."WebUsers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."WebUsers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: WebUsers; Type: TABLE DATA; Schema: public; Owner: sergey
--

COPY public."WebUsers" ("Id", "Name") FROM stdin;
2	Андрей
1	Сергей Александрович
\.


--
-- Name: WebUsers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: sergey
--

SELECT pg_catalog.setval('public."WebUsers_Id_seq"', 3, true);


--
-- Name: WebUsers PK_WebUsers; Type: CONSTRAINT; Schema: public; Owner: sergey
--

ALTER TABLE ONLY public."WebUsers"
    ADD CONSTRAINT "PK_WebUsers" PRIMARY KEY ("Id");


--
-- PostgreSQL database dump complete
--

\unrestrict x0QVCea51D2EJqKtAAJ0Jtjz4Fl85WzT027S925BYI1pnhY5e9Sc2QZzVYZGTrp

